# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0300c0a0c211d81d7361ab1275c973d"
name = "slideit-bnpl"
handle = "slideit-bnpl-3"
application_url = "https://slideit-bnpl.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_orders"

[auth]
redirect_urls = ["https://slideit-bnpl.vercel.app//auth/callback", "https://slideit-bnpl.vercel.app//auth/shopify/callback", "https://slideit-bnpl.vercel.app//api/auth/callback"]

[pos]
embedded = false
